"""Local file store for task-scoped thread journals and compaction state."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any


@dataclass(eq=True)
class ThreadCompactionState:
    """Persisted derived state for rolling thread compaction."""

    compacted_summary: str = ""
    last_compacted_message_id: str | None = None
    last_compacted_timestamp: str | None = None
    source_message_ids: list[str] = field(default_factory=list)
    message_count_since_compaction: int = 0
    char_count_since_compaction: int = 0
    summary_token_budget: int = 20_000
    recent_window_messages: int = 15
    last_journal_message_id: str | None = None


class ThreadJournalStore:
    """Read and write the Markdown journal and JSON compaction state."""

    def __init__(self, journal_path: Path, state_path: Path | None = None) -> None:
        self.journal_path = journal_path
        self.state_path = (
            state_path
            if state_path is not None
            else journal_path.with_name("THREAD_COMPACTION_STATE.json")
        )

    def write_journal_header(
        self,
        *,
        task_title: str,
        task_id: str,
        created_at: str,
        updated_at: str,
        status: str,
        assigned_agent: str,
        board_name: str | None,
        workflow_spec: str | None,
        plan_generated_by: str | None,
        execution_plan_markdown: str,
    ) -> None:
        """Write or replace the stateful journal header sections."""
        self._ensure_parent_dirs()
        existing_events = self._read_thread_events_section()
        lines = [
            "# Thread Journal",
            f"- Task: {task_title}",
            f"- Task ID: {task_id}",
            f"- Created: {created_at}",
            f"- Last Updated: {updated_at}",
            "",
            "## Task Snapshot",
            f"- Status: {status}",
            f"- Assigned Agent: {assigned_agent}",
            f"- Board: {board_name or ''}",
            f"- Workflow Spec: {workflow_spec or ''}",
            f"- Plan Generated By: {plan_generated_by or ''}",
            "",
            "## Execution Plan",
            execution_plan_markdown or "(none)",
            "",
            "## Thread Events",
        ]
        text = "\n".join(lines).rstrip() + "\n"
        if existing_events:
            text += "\n" + existing_events.lstrip("\n")
        self._atomic_write_text(self.journal_path, text)

    def append_event(
        self,
        *,
        timestamp: str,
        author_name: str,
        author_type: str,
        event_type: str,
        content: str,
        step_id: str | None = None,
        artifacts: list[dict[str, Any]] | None = None,
    ) -> None:
        """Append a single event to the journal's thread-events section."""
        self._ensure_parent_dirs()
        if not self.journal_path.exists():
            raise FileNotFoundError(
                f"Journal header must exist before appending: {self.journal_path}"
            )

        title = f"### {timestamp} | {author_name} | {event_type}"
        if step_id:
            title += f" | step={step_id}"

        lines = [title, content]
        if artifacts:
            lines.append("Artifacts:")
            for artifact in artifacts:
                action = str(artifact.get("action", "unknown")).upper()
                path = str(artifact.get("path", "unknown"))
                lines.append(f"- {action}: {path}")

        with self.journal_path.open("a", encoding="utf-8") as handle:
            handle.write("\n" + "\n".join(lines).rstrip() + "\n")

    def read_state(self) -> ThreadCompactionState:
        """Load the persisted compaction state or return the default state."""
        if not self.state_path.exists():
            return ThreadCompactionState()
        data = json.loads(self.state_path.read_text(encoding="utf-8"))
        return ThreadCompactionState(**data)

    def write_state(self, state: ThreadCompactionState) -> None:
        """Persist compaction state atomically."""
        self._ensure_parent_dirs()
        self._atomic_write_text(
            self.state_path,
            json.dumps(asdict(state), indent=2, ensure_ascii=False) + "\n",
        )

    def _ensure_parent_dirs(self) -> None:
        self.journal_path.parent.mkdir(parents=True, exist_ok=True)
        self.state_path.parent.mkdir(parents=True, exist_ok=True)

    def _read_thread_events_section(self) -> str:
        if not self.journal_path.exists():
            return ""
        text = self.journal_path.read_text(encoding="utf-8")
        marker = "## Thread Events\n"
        if marker not in text:
            return ""
        _, _, suffix = text.partition(marker)
        return suffix

    @staticmethod
    def _atomic_write_text(path: Path, content: str) -> None:
        """Write text atomically to avoid partial state files."""
        with NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            delete=False,
        ) as handle:
            handle.write(content)
            temp_path = Path(handle.name)
        temp_path.replace(path)
